### PR TITLE
First round of fixes for french langage

### PR DESCRIPTION
**Pull request by Elementtair**
Fixes some obvious errors in the translation

### CODE REVIEW

**Comment by MioVisman** [comment]
Thank you!

**Comment by Elementtair** [comment]
Also not directly related but I saw that when translating.
Recommended size for avatar is 60, 60, 10240
https://github.com/forkbb/forkbb/blob/2a78f57a63d3b9e984316acf74b54b3351483362/app/lang/en/admin_options.po#L225-L239
When the default setup make them 160, 160, 51200
https://github.com/forkbb/forkbb/blob/2a78f57a63d3b9e984316acf74b54b3351483362/app/Models/Pages/Admin/Install.php#L1579-L1581

**Comment by MioVisman** [comment]
I think it's not a big deal. Each admin can set their own values ​​for their forum. Perhaps the recommended values ​​should be removed from the language files.

**Comment by Elementtair** [comment]
Yes, not a big deal: that's why I didn't opened an issue. Just a matter of consistency.
Removing the recommended values would do it !

**Comment by MioVisman** [comment]
https://github.com/forkbb/forkbb/commit/907ef1869a70e48469c0b39181098b23dbbb07bb

**Pull request merged**
