### PR TITLE
Add french langage to Forkbb

### PR DESCRIPTION
**Pull request by Elementtair**
French translations for forkbb.

Will try to do a follow up PR once I will have find all typos and approximation.

It was tested on a local instalation but I surely missed some stuff 

Cheers !

### CODE REVIEW

**Comment by Elementtair** [comment]
I used the code &#8217 for the single quote, which is not traduced in button
Capture d’écran 2024-11-07 130158

Is it a wrong usage or a bug ?

**Comment by MioVisman** [comment]
The semicolon is missing, but the & character is actually escaped.
```
<button class="f-btn f-fbtn" type="submit" name="login" value="S&amp;#8217authentifier" title="S&amp;#8217authentifier"><span>S&amp;#8217authentifier</span></button>
```

I think it would be more correct to replace Decimal Code with a Unicode symbol.

**Comment by Elementtair** [comment]
Ok

You'd prefer with `&#x2019;` ?

**Comment by MioVisman** [comment]
I don't see any visual difference in these symbols.

**Comment by Elementtair** [comment]
Yes, no visual difference.
 I thought it was what you were meaning by unicode instead of decimal

**Comment by MioVisman** [comment]
replace

**Comment by MioVisman** [comment]
fix

**Comment by Elementtair** [comment]
Ok. I understand know what you meant, single quote didn't need to be escaped. Thank for the correction and the merge.

I already started to work on a follow up PR cause there is still a lot of typos, conjugation and stuff like that I did wrong

**Pull request merged**
